FROM python:3.7-alpine


ENV PYTHONUNBUFFERED=1

RUN apk add gcc musl-dev

ADD ./backend /backend
WORKDIR /backend

RUN pip install gunicorn gevent
RUN pip install -r requirements.txt

ADD ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD gunicorn -b 0.0.0.0:$PORT --worker-class gevent --worker-connections 1024 app:app