FROM python:3.7-alpine


ENV PYTHONUNBUFFERED=1

RUN apk add gcc musl-dev
RUN apk add mariadb-dev build-base


ADD ./backend /backend
WORKDIR /backend

RUN pip install gunicorn gevent
RUN pip install -r requirements.txt

EXPOSE 80