FROM python:3.7-alpine


ENV PYTHONUNBUFFERED=1

RUN apk add gcc musl-dev

ADD ./frontend /test
WORKDIR /test

RUN pip install gunicorn gevent
RUN pip install -r requirements.txt

CMD gunicorn -b 0.0.0.0:31337--worker-class gevent --worker-connections 1024 app:app